### ISSUE TITLE
Add hover text to Unfinishedlabs.io link

### ISSUE THREAD

**Issue by dduncanmccourt** [LibertyDSNP/liberty-web#12]
Hi -
Please add this hover text to the UnfinishedLabs.io link in the footer.
"You are now leaving the Project Liberty website"

Thanks!
Denise

**Comment by kfogel** [comment]
I'm going out on a limb and "assigning" this to @claireolmstead -- "assign" in quotes because I have no authority to do so, and also because I'm not 100% sure that Claire's the (or a) right person.  But I'm pretty sure that either she is or she knows who would be better to re-assign to.  So, this is just to start the ball rolling.

(Or if this issue is no longer relevant due to redesign, then let's close it.)

**Comment by claireclark1** [comment]
> I'm going out on a limb and "assigning" this to @claireolmstead -- "assign" in quotes because I have no authority to do so, and also because I'm not 100% sure that Claire's the (or a) right person. But I'm pretty sure that either she is or she knows who would be better to re-assign to. So, this is just to start the ball rolling.
> 
> (Or if this issue is no longer relevant due to redesign, then let's close it.)

This was not a part of the redesign, but will add it to pivotal and make sure to get this change in. Thank you for bringing it to my attention @kfogel

**Comment by claireclark1** [comment]
this is now on the project-liberty-web branch
